# Generated by Django 3.2.12 on 2023-12-10 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=255)),
                ('country_flag', models.URLField()),
                ('country_currency', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=255)),
                ('price_per_kilo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipping.country')),
            ],
        ),
    ]
